### ISSUE TITLE
WebSocket connection to 'ws://localhost:8080/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by suryamishra59** [jmlw/demo-projects#1]
The console gives me following while opening a connection
`WebSocket connection to 'ws://localhost:8080/websocket' failed: Error during WebSocket handshake: Unexpected response code: 404`

Following is the Config file as you described in your blog
`package com.websocket.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.messaging.simp.config.MessageBrokerRegistry;
import org.springframework.web.socket.config.annotation.EnableWebSocketMessageBroker;
import org.springframework.web.socket.config.annotation.StompEndpointRegistry;
import org.springframework.web.socket.config.annotation.WebSocketMessageBrokerConfigurer;

@Configuration
@EnableWebSocketMessageBroker
public class WebSocketConfig implements WebSocketMessageBrokerConfigurer {

	@Override
	public void configureMessageBroker(MessageBrokerRegistry config) {
		config.enableSimpleBroker("/topic");
		config.setApplicationDestinationPrefixes("/app");
	}

	@Override
	public void registerStompEndpoints(StompEndpointRegistry registry) {
		registry.addEndpoint("/websocket");
		registry.addEndpoint("/sockjs").withSockJS();
	}
}
`

**Comment by jmlw** [comment]
From the server response, it seems that your server is responding correctly from localhost:8080, but the `/websocket` endpoint as defined in the config you referenced has not been registered. 

Please double check that your Spring application has component scanning enabled, and that this configuration component is being created & the `registerStompEndpoints` method is called during application initialization by logging or printing a debug report for Spring.

I've just tested with the latest commit on _master_ from this project and am not able to reproduce so it is most likely a problem specific to your project.

**Comment by suryamishra59** [comment]
Oh, yes! Silly mistake. The endpoint as defined in the config was not being registered,
